### ISSUE TITLE
Going directly to /riders/ID/edit causes an internal service error

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#173]
E.g. https://dispatch.bikebrigade.ca/riders/123/edit will break the site.

I think we're forgetting to load something in `mount` that's just being done in `apply_action`?

**Comment by teesloane** [comment]
This is happening because we have a `live` [route for RidersLiveIndex](https://github.com/bikebrigade/dispatch/blob/e217861165c68a4f928fa01f9d99f74afe596dab/lib/bike_brigade_web/router.ex#L118) wth an :edit action, but never handle the :edit action. 

There is [one place](https://github.com/bikebrigade/dispatch/blob/e217861165c68a4f928fa01f9d99f74afe596dab/lib/bike_brigade/tasks/mailchimp_importer.ex#L117) in the codebase that uses (or rather, suggests to use) this route. 

We could either remove the route (and update the above) or we could push a redirect to the existing riders [show/edit route](https://github.com/bikebrigade/dispatch/blob/e217861165c68a4f928fa01f9d99f74afe596dab/lib/bike_brigade_web/router.ex#L153).

Let me know what you'd like, @mveytsman and I'll toss up a PR.

**Comment by mveytsman** [comment]
Good catch!

Could we remove the route and update the above line with the correct route?
