### ISSUE TITLE
Add a field to programs/campaigns to capture what to do when recipients are not home

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#196]
Notes from @chadmohr 
General rule per program/campaign
Override for recipient specific notes (?)

Options for general rules:
- leave at door
- Contact bb (if it's in the app - this should be a link that opens up texts)
- Contact partner (do we put a phone number here?)
- Deliver to community fridge
- Maybe free form field with like 200 character limit?
- Empty (like fridges)

Display for rider
- box between pickup and delivery

**Comment by teesloane** [comment]
Do we still want this? If so, My understanding is this would look something like this for the rider:

![CleanShot 2023-11-01 at 07 58 53@2x](https://github.com/bikebrigade/dispatch/assets/12987958/37a41f74-dd07-4129-96bb-7ea8b69b98a5)

**Implementation:**

To do this, I'm guessing when a program/campaign is created we would add a drop down with those general rules (and a free form field if you select "other") — then in the db would need to add a column to both programs and campaigns ("recipient_not_home_option", or whatever) to hold those values (it being the case that the _program_ would set the default opeion, and the campaign would inherit that with the option to override it on a campaign per campaign basis?)

![CleanShot 2023-11-01 at 08 04 14@2x](https://github.com/bikebrigade/dispatch/assets/12987958/50fc4587-1916-4334-845b-a45d9432bef7)

**Comment by chadmohr** [comment]
Good question @teesloane.  I'm not sure this is very important because the 90% of the time the rule is to leave at door. Plus most campaign leads just use the notes field for individual tasks if the expectation is otherwise.

Having said that, your assessment of the task is mostly correct. The initial idea, however, may have been ill conceived. A plain text field is probably better than select options. If we do put an default **campaign** rules, tasks would need a text field at the task level to override it.

**Comment by teesloane** [comment]
Thanks @chadmohr . I'm going to close this @mveytsman but please re-open now/later if you think it's pertinent!
