### ISSUE TITLE
Improve disconnected errors (on mobile)

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#203]
This ticket is about two things

1) We're going to be disconnected when the app is backgrounded on mobile. Right now, our error is a little too aggressive / jarring. We should make it say something like "Reconnecting" and be a warn instead of a red error. 

![image](https://user-images.githubusercontent.com/34720/206518939-324a5d9b-1117-4f39-8e08-7c8475f22384.png)

See [this comment from Chris](https://news.ycombinator.com/item?id=28623250) for more context

2) The flash error above is too wide on mobile, we should make it narrower. It's from the Phoenix default templates, and they may have changed the styling since I last looked...

**Comment by teesloane** [comment]
How's this as an option?

- adds a"warn" @kind
- uses @close since it blocks the menu
- moves everything onto one line.  

https://user-images.githubusercontent.com/12987958/206532130-3139016f-0c43-47b6-a6d6-16cf0360587f.mp4

Haven't tested this with other flash messages across the app yet to see how they look, tho.
